package main

import (
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"
)

// composeFor renders the docker-compose file for a project's local cognates
// and the env contract the app sees. Cognate versions are pinned to match
// what the platform provisions remotely (Aurora PostgreSQL 16 → postgres:16).
func composeFor(project string, resources []resource) (composeYAML string, env map[string]string) {
	env = map[string]string{}
	services := []string{}
	volumes := []string{}
	dbSeen, storageSeen := false, false

	for _, r := range resources {
		switch r.Type {
		case "database":
			p := port(project, r.Name, "pg")
			db := strings.ReplaceAll(project, "-", "_") + "_" + r.Name
			services = append(services, fmt.Sprintf(`  db-%s:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: platform
      POSTGRES_DB: %s
    ports: ["%d:5432"]
    volumes: ["db-%s:/var/lib/postgresql/data"]`, r.Name, db, p, r.Name))
			volumes = append(volumes, "db-"+r.Name)
			url := fmt.Sprintf("postgres://postgres:platform@localhost:%d/%s?sslmode=disable", p, db)
			env["PLATFORM_DATABASE_"+strings.ToUpper(r.Name)+"_URL"] = url
			if !dbSeen {
				env["DATABASE_URL"] = url
				dbSeen = true
			}
		case "storage":
			p := port(project, r.Name, "s3")
			services = append(services, fmt.Sprintf(`  storage-%s:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: platform
      MINIO_ROOT_PASSWORD: platform-secret
    ports: ["%d:9000"]
    volumes: ["storage-%s:/data"]`, r.Name, p, r.Name))
			volumes = append(volumes, "storage-"+r.Name)
			if !storageSeen {
				env["STORAGE_ENDPOINT"] = fmt.Sprintf("http://localhost:%d", p)
				env["STORAGE_ACCESS_KEY"] = "platform"
				env["STORAGE_SECRET_KEY"] = "platform-secret"
				env["STORAGE_BUCKET"] = r.Name
				storageSeen = true
			}
		}
	}

	if len(services) == 0 {
		return "", env
	}
	var b strings.Builder
	b.WriteString("# generated by 'platform dev' from platform.yaml — do not edit\nservices:\n")
	b.WriteString(strings.Join(services, "\n") + "\n")
	b.WriteString("volumes:\n")
	for _, v := range volumes {
		b.WriteString("  " + v + ":\n")
	}
	return b.String(), env
}

func devUp() error {
	project, err := projectName()
	if err != nil {
		return err
	}
	m, err := loadManifest()
	if err != nil {
		return err
	}
	resources := m.resources()

	if err := os.MkdirAll(".platform", 0o755); err != nil {
		return err
	}
	compose, env := composeFor(project, resources)
	if err := writeEnvFile(env); err != nil {
		return err
	}

	if compose == "" {
		fmt.Println("no resources in platform.yaml yet — nothing to start")
		fmt.Println("add one with: platform add database main")
		return nil
	}
	if err := os.WriteFile(".platform/compose.yaml", []byte(compose), 0o644); err != nil {
		return err
	}
	cmd := exec.Command("docker", "compose", "-p", "platform-"+project, "-f", ".platform/compose.yaml", "up", "-d")
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("docker compose failed — is Docker running?")
	}

	fmt.Println("\nlocal cognates up. environment contract (.platform/env):")
	printEnv(env)
	fmt.Println("\nrun your app with it: platform run -- <command>")
	return nil
}

func writeEnvFile(env map[string]string) error {
	keys := sortedKeys(env)
	var b strings.Builder
	for _, k := range keys {
		b.WriteString(k + "=" + env[k] + "\n")
	}
	return os.WriteFile(".platform/env", []byte(b.String()), 0o644)
}

func loadEnvFile() ([]string, error) {
	b, err := os.ReadFile(".platform/env")
	if err != nil {
		return nil, fmt.Errorf("no .platform/env — run 'platform dev' first")
	}
	lines := []string{}
	for _, l := range strings.Split(strings.TrimSpace(string(b)), "\n") {
		if l != "" {
			lines = append(lines, l)
		}
	}
	return lines, nil
}

func printEnv(env map[string]string) {
	for _, k := range sortedKeys(env) {
		fmt.Printf("  %s=%s\n", k, env[k])
	}
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
